services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: ga4_postgres
    environment:
      POSTGRES_USER: ga4_user
      POSTGRES_PASSWORD: ga4_password
      POSTGRES_DB: ga4_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  qdrant_data:
  postgres_data:
